# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dots < Formula
  desc "Interactive frontend for the Nix-managed dotfiles environment."
  homepage "https://github.com/sanurb/.dotfiles"
  version "0.6.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sanurb/.dotfiles/releases/download/v0.6.4/dots_0.6.4_darwin_amd64.tar.gz"
      sha256 "5a2886b25e8845376170976d72f7dd338976a9c74173e78ab27064328964b8dc"

      define_method(:install) do
        bin.install "dots"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sanurb/.dotfiles/releases/download/v0.6.4/dots_0.6.4_darwin_arm64.tar.gz"
      sha256 "7b5e67acff75acf650a490dcf0ba0d1e0d22445f2080060817e9976af0f7c18c"

      define_method(:install) do
        bin.install "dots"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanurb/.dotfiles/releases/download/v0.6.4/dots_0.6.4_linux_amd64.tar.gz"
      sha256 "8e7fb56b8bbc44c9b8c1fb10db6cc2ae266cfbf8ff9e2da315d5265c7ebc39d6"
      define_method(:install) do
        bin.install "dots"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanurb/.dotfiles/releases/download/v0.6.4/dots_0.6.4_linux_arm64.tar.gz"
      sha256 "0413ed68d1169ca39b8af0dbc03ea70cffe73c521e3cc67c16003ae50e88bd15"
      define_method(:install) do
        bin.install "dots"
      end
    end
  end

  test do
    assert_match "dots", shell_output("#{bin}/dots --version")
  end
end
