# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dots < Formula
  desc "Interactive frontend for the Nix-managed dotfiles environment."
  homepage "https://github.com/sanurb/.dotfiles"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sanurb/.dotfiles/releases/download/v0.11.1/dots_0.11.1_darwin_amd64.tar.gz"
      sha256 "b76123d3a4a6ad25a95e9fbd19810170cf0de27123861d3d735e8d221e48506e"

      define_method(:install) do
        bin.install "dots"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sanurb/.dotfiles/releases/download/v0.11.1/dots_0.11.1_darwin_arm64.tar.gz"
      sha256 "c72efa04f149a2408cd4ad9254a5906ea923b82abc155a043a5fec65612cb6d4"

      define_method(:install) do
        bin.install "dots"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanurb/.dotfiles/releases/download/v0.11.1/dots_0.11.1_linux_amd64.tar.gz"
      sha256 "847005fca1d24ae442052e7fd22740f5a2288075f747a4f3d9f5204a22dadee4"
      define_method(:install) do
        bin.install "dots"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanurb/.dotfiles/releases/download/v0.11.1/dots_0.11.1_linux_arm64.tar.gz"
      sha256 "94a15aff4ea4b634d6252b96d2f137e30c2aa7cc394c263b56338dfbd5d38b11"
      define_method(:install) do
        bin.install "dots"
      end
    end
  end

  test do
    assert_match "dots", shell_output("#{bin}/dots --version")
  end
end
