# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dots < Formula
  desc "Interactive frontend for the Nix-managed dotfiles environment."
  homepage "https://github.com/sanurb/.dotfiles"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sanurb/.dotfiles/releases/download/v0.4.1/dots_0.4.1_darwin_amd64.tar.gz"
      sha256 "f812e9d81de8c9c19d023db79a1d030d797ae8e56432506933c578e8ccebd175"

      define_method(:install) do
        bin.install "dots"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sanurb/.dotfiles/releases/download/v0.4.1/dots_0.4.1_darwin_arm64.tar.gz"
      sha256 "b8a15099291bf9844cabbd902ca9af27a4cd952c86ff2cacdbed03baf98743fd"

      define_method(:install) do
        bin.install "dots"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanurb/.dotfiles/releases/download/v0.4.1/dots_0.4.1_linux_amd64.tar.gz"
      sha256 "2c786832e8ccda1a07ffc1fda196076a07df29dabee3df116bc254d56f7f2dc0"
      define_method(:install) do
        bin.install "dots"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sanurb/.dotfiles/releases/download/v0.4.1/dots_0.4.1_linux_arm64.tar.gz"
      sha256 "ef62abd006f1d34a5062c8c6defac7b1501b632ca9a15b0067cd430da278be20"
      define_method(:install) do
        bin.install "dots"
      end
    end
  end

  test do
    assert_match "dots", shell_output("#{bin}/dots --version")
  end
end
