# This file was generated by GoReleaser. DO NOT EDIT.
cask "dots" do
  version "0.17.0"

  on_macos do
    on_arm do
      sha256 "69cbaa6c51d4b5d61c73071a356bfcef262903bf1f949343b132fd281a978bbb"
      url "https://github.com/sanurb/.dotfiles/releases/download/v#{version}/dots_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fce2bd19410c36c4b1550362c0b18d9798951c028c04a220441caa172601901c"
      url "https://github.com/sanurb/.dotfiles/releases/download/v#{version}/dots_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f941f1a50d327f43e9fb55038cfa379b3c4ea1352c4ba5e3e5ba9aecb4270ff9"
      url "https://github.com/sanurb/.dotfiles/releases/download/v#{version}/dots_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9944cfb9111c31bf875c27e5bafcfc146f7fc45e1723a425e7fe1f86aac87eca"
      url "https://github.com/sanurb/.dotfiles/releases/download/v#{version}/dots_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dots"
  desc "Interactive frontend for the Nix-managed dotfiles environment."
  homepage "https://github.com/sanurb/.dotfiles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dots"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dots"]
    end
  end

  # No zap stanza required
end
