# This file was generated by GoReleaser. DO NOT EDIT.
cask "dots" do
  version "0.17.1"

  on_macos do
    on_arm do
      sha256 "97ded4723aeae594082d722bf5037b3435b2bc362621e32ae4ccb50004bf6b83"
      url "https://github.com/sanurb/.dotfiles/releases/download/v#{version}/dots_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d6e9c43bde1933d563ac9904e2c842e7ac21227147e7021789fc53c0aa6f7bc8"
      url "https://github.com/sanurb/.dotfiles/releases/download/v#{version}/dots_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "39f0dc67f63343784e9cdcb70c397407713d4055b7182309188d0eb7f4c234bc"
      url "https://github.com/sanurb/.dotfiles/releases/download/v#{version}/dots_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "60765e10875aad3ebfea50220bdc33ead9069758bbe1a99f89c79ff9789a2eca"
      url "https://github.com/sanurb/.dotfiles/releases/download/v#{version}/dots_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dots"
  desc "Interactive frontend for the Nix-managed dotfiles environment."
  homepage "https://github.com/sanurb/.dotfiles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dots"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dots"]
    end
  end

  # No zap stanza required
end
