# This file was generated by GoReleaser. DO NOT EDIT.
cask "dots" do
  version "0.15.1"

  on_macos do
    on_arm do
      sha256 "84e94b37537c12c485bfb3f9889ae0a27179ce63d495f723d26d8bf0e97943d7"
      url "https://github.com/sanurb/.dotfiles/releases/download/v#{version}/dots_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0c4ea18bee13fe7b553a9ae943a349b2ee7c92d1bc5ff12fb6c4db082cd39c19"
      url "https://github.com/sanurb/.dotfiles/releases/download/v#{version}/dots_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "95584d3d0c0c1d271b6caeb3b4e812a45a4a0a56fd39dab8f1b148901b212a2e"
      url "https://github.com/sanurb/.dotfiles/releases/download/v#{version}/dots_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "43d1f1c513426af108d10eb5f019db5ca7eb13ff216b0d4d19ab179c6c2f2354"
      url "https://github.com/sanurb/.dotfiles/releases/download/v#{version}/dots_#{version}_linux_amd64.tar.gz"
    end
  end

  name "dots"
  desc "Interactive frontend for the Nix-managed dotfiles environment."
  homepage "https://github.com/sanurb/.dotfiles"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dots"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dots"]
    end
  end

  # No zap stanza required
end
